apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-practice-1
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: deploy-practice-2
        image: shavbb/deploy-practice-2:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always