apiVersion: v1
kind: Service
metadata:
  name: deploy-practice-1-service
  namespace: dev
spec:
  selector:
    app: prod-app
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30010
  
  