name: CI Pipeline - Build and Test

on:
  push: 
    paths:
      - '02-ci-build-and-test/**'
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: 02-ci-build-and-test
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: list the project files
        run: ls -la  

      - name: Build Docker Image
        run: docker build -t cicd-prod .

      - name: Run Container
        run: docker run -d -p 5000:5000 --name prod-container cicd-prod

      - name: Wait for app
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "App is up"
              exit 0
            fi
              echo "Waiting for app..."
              sleep 2
          done

          echo "App failed to start"
          exit 1
      
      - name: Real health check
        run: curl -f http://localhost:5000

      - name: Clean up
        if: always()
        run: docker stop prod-container && docker rm prod-container
