name: Deploy pipeline

on: 
  push:
    paths:
      - '04-deploy-success-but-app-down/**'
    branch:
      - dev

jobs:
  deploy-pipeline:
    runs-on: self-hosted
  
    defaults:
      run:
        working-directory: '04-deploy-success-but-app-down'

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: List project files
        run: ls -la
      
      - name: Build image
        run: docker build -t deploy-pipeline .

      - name: Run container
        run: docker run -d -p 5000:5000 -e API_KEY=${API_KEY} --name prod-deploy-con deploy-pipeline

      - name: Wait for app
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "App is running"
              echo 0
            fi
              echo "Waiting for app"
              sleep 2
          done

          echo "app is not working"
          exit 1
      
      - name: logs
        run: docker logs prod-deploy-con

      - name: Check app isRunning
        run: curl -f http://localhost:5000
      
      - name: Deployment success message
        run: echo "Deployment successful"