name: Deploy pipeline

on: 
  push:
    paths:
      - '05-k8s-deployment/**'
    branches:
      - dev

jobs:
  build-pipeline:
    runs-on: self-hosted
  
    defaults:
      run:
        working-directory: '05-k8s-deployment'

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: List project files
      run: ls -la
    
    - name: Login to Docker hub
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build image and Push
      run: |
        docker build -t $DOCKER_USERNAME/deploy-pipeline:${{ github.sha }} \
                     -t $DOCMER_USERNAME/deploy-pipeline:latest .
        docker push $DOCKER_USERNAME/deploy-pipeline:${{ github.sha }}
        docker push $DOKCER_USERNAME/deploy-pipeline:latest
  
  deploy:
    runs-on: self-hosted
    needs: build-pipeline

    defaults:
      run:
        working-directory: '05-k8s-deployment'

    env: 
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: setup kube config
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to k8s
      run: |
        kubectl apply -f k8s/deployment.yaml --namespace dev
        kubectl apply -f k8s/service.yaml --namespace dev
    
    - name: Wait for Deployment
      run: kubectl rollout status deployment/prod-app

    - name: Clean up kube config
      if: always()
      run: rm -f ~/.kube/config