name: CI - securiy and secrets

on:
  push:
    paths: 
      - '03-security-and-secrets/**'
    branch:
      - dev

jobs:
  security-and-secret:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: 03-security-and-secrets

    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: list project files
      run: echo ls -la
    
    - name: docker build
      run: docker build -t cicd-security-secret .

    - name: Container run
      run: docker run -d -p 5000:5000 prod-container cicd-security-secret 

    - name: Wait for app
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5000; then
            echo "App is running"
            exit 0
          fi 
            echo "echo waiting for app"
            sleep 2
        done

        echo "App is not working"
        exit 1

    - name: Real health check
      run: curl -f http://localhost:5000

    - name: Clean up
      run: docker stop prod-container && docker rm prod-container
            